//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sFTP2.webservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginData", Namespace="http://dockmanager.eu/")]
    [System.SerializableAttribute()]
    public partial class LoginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBooking", Namespace="http://dockmanager.eu/", ItemName="booking")]
    [System.SerializableAttribute()]
    public class ArrayOfBooking : System.Collections.Generic.List<sFTP2.webservice.booking> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="booking", Namespace="http://dockmanager.eu/")]
    [System.SerializableAttribute()]
    public partial class booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errormessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reference2Field;
        
        private int ent_idField;
        
        private System.DateTime dt_plannedField;
        
        private System.DateTime dt1Field;
        
        private System.DateTime dt2Field;
        
        private System.DateTime dt3Field;
        
        private System.DateTime dt4Field;
        
        private System.DateTime dt5Field;
        
        private System.DateTime dt6Field;
        
        private System.DateTime dt7Field;
        
        private System.DateTime dt8Field;
        
        private System.DateTime dtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sit_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string car_nameField;
        
        private int actionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errormessage {
            get {
                return this.errormessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errormessageField, value) != true)) {
                    this.errormessageField = value;
                    this.RaisePropertyChanged("errormessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                if ((object.ReferenceEquals(this.referenceField, value) != true)) {
                    this.referenceField = value;
                    this.RaisePropertyChanged("reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string reference2 {
            get {
                return this.reference2Field;
            }
            set {
                if ((object.ReferenceEquals(this.reference2Field, value) != true)) {
                    this.reference2Field = value;
                    this.RaisePropertyChanged("reference2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ent_id {
            get {
                return this.ent_idField;
            }
            set {
                if ((this.ent_idField.Equals(value) != true)) {
                    this.ent_idField = value;
                    this.RaisePropertyChanged("ent_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime dt_planned {
            get {
                return this.dt_plannedField;
            }
            set {
                if ((this.dt_plannedField.Equals(value) != true)) {
                    this.dt_plannedField = value;
                    this.RaisePropertyChanged("dt_planned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime dt1 {
            get {
                return this.dt1Field;
            }
            set {
                if ((this.dt1Field.Equals(value) != true)) {
                    this.dt1Field = value;
                    this.RaisePropertyChanged("dt1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime dt2 {
            get {
                return this.dt2Field;
            }
            set {
                if ((this.dt2Field.Equals(value) != true)) {
                    this.dt2Field = value;
                    this.RaisePropertyChanged("dt2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime dt3 {
            get {
                return this.dt3Field;
            }
            set {
                if ((this.dt3Field.Equals(value) != true)) {
                    this.dt3Field = value;
                    this.RaisePropertyChanged("dt3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime dt4 {
            get {
                return this.dt4Field;
            }
            set {
                if ((this.dt4Field.Equals(value) != true)) {
                    this.dt4Field = value;
                    this.RaisePropertyChanged("dt4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime dt5 {
            get {
                return this.dt5Field;
            }
            set {
                if ((this.dt5Field.Equals(value) != true)) {
                    this.dt5Field = value;
                    this.RaisePropertyChanged("dt5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime dt6 {
            get {
                return this.dt6Field;
            }
            set {
                if ((this.dt6Field.Equals(value) != true)) {
                    this.dt6Field = value;
                    this.RaisePropertyChanged("dt6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime dt7 {
            get {
                return this.dt7Field;
            }
            set {
                if ((this.dt7Field.Equals(value) != true)) {
                    this.dt7Field = value;
                    this.RaisePropertyChanged("dt7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime dt8 {
            get {
                return this.dt8Field;
            }
            set {
                if ((this.dt8Field.Equals(value) != true)) {
                    this.dt8Field = value;
                    this.RaisePropertyChanged("dt8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.DateTime dt {
            get {
                return this.dtField;
            }
            set {
                if ((this.dtField.Equals(value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string sit_name {
            get {
                return this.sit_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.sit_nameField, value) != true)) {
                    this.sit_nameField = value;
                    this.RaisePropertyChanged("sit_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string car_name {
            get {
                return this.car_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.car_nameField, value) != true)) {
                    this.car_nameField = value;
                    this.RaisePropertyChanged("car_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int action {
            get {
                return this.actionField;
            }
            set {
                if ((this.actionField.Equals(value) != true)) {
                    this.actionField = value;
                    this.RaisePropertyChanged("action");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallOff", Namespace="http://dockmanager.eu/")]
    [System.SerializableAttribute()]
    public partial class CallOff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private sFTP2.webservice.LoginData loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageNumberField;
        
        private System.DateTime messageDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipperIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipperNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string goods_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipperRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierRefField;
        
        private double NweightField;
        
        private double GweightField;
        
        private double LMField;
        
        private double CountField;
        
        private double VolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VolumeUnitField;
        
        private double PalletsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierInstructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sFTP2.webservice.ArrayOfLocationStruct locationsField;
        
        private sFTP2.webservice.carrierStruct carrierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sFTP2.webservice.ArrayOfReferenceStruct referenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public sFTP2.webservice.LoginData login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageNumber {
            get {
                return this.MessageNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageNumberField, value) != true)) {
                    this.MessageNumberField = value;
                    this.RaisePropertyChanged("MessageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime messageDateTime {
            get {
                return this.messageDateTimeField;
            }
            set {
                if ((this.messageDateTimeField.Equals(value) != true)) {
                    this.messageDateTimeField = value;
                    this.RaisePropertyChanged("messageDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ShipperID {
            get {
                return this.ShipperIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipperIDField, value) != true)) {
                    this.ShipperIDField = value;
                    this.RaisePropertyChanged("ShipperID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ShipperName {
            get {
                return this.ShipperNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipperNameField, value) != true)) {
                    this.ShipperNameField = value;
                    this.RaisePropertyChanged("ShipperName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string action {
            get {
                return this.actionField;
            }
            set {
                if ((object.ReferenceEquals(this.actionField, value) != true)) {
                    this.actionField = value;
                    this.RaisePropertyChanged("action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string goods_description {
            get {
                return this.goods_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.goods_descriptionField, value) != true)) {
                    this.goods_descriptionField = value;
                    this.RaisePropertyChanged("goods_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ShipperRef {
            get {
                return this.ShipperRefField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipperRefField, value) != true)) {
                    this.ShipperRefField = value;
                    this.RaisePropertyChanged("ShipperRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string OrderRef {
            get {
                return this.OrderRefField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderRefField, value) != true)) {
                    this.OrderRefField = value;
                    this.RaisePropertyChanged("OrderRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string CarrierRef {
            get {
                return this.CarrierRefField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierRefField, value) != true)) {
                    this.CarrierRefField = value;
                    this.RaisePropertyChanged("CarrierRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double Nweight {
            get {
                return this.NweightField;
            }
            set {
                if ((this.NweightField.Equals(value) != true)) {
                    this.NweightField = value;
                    this.RaisePropertyChanged("Nweight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public double Gweight {
            get {
                return this.GweightField;
            }
            set {
                if ((this.GweightField.Equals(value) != true)) {
                    this.GweightField = value;
                    this.RaisePropertyChanged("Gweight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public double LM {
            get {
                return this.LMField;
            }
            set {
                if ((this.LMField.Equals(value) != true)) {
                    this.LMField = value;
                    this.RaisePropertyChanged("LM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public double Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public double Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string VolumeUnit {
            get {
                return this.VolumeUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.VolumeUnitField, value) != true)) {
                    this.VolumeUnitField = value;
                    this.RaisePropertyChanged("VolumeUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public double Pallets {
            get {
                return this.PalletsField;
            }
            set {
                if ((this.PalletsField.Equals(value) != true)) {
                    this.PalletsField = value;
                    this.RaisePropertyChanged("Pallets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string CarrierInstructions {
            get {
                return this.CarrierInstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierInstructionsField, value) != true)) {
                    this.CarrierInstructionsField = value;
                    this.RaisePropertyChanged("CarrierInstructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public sFTP2.webservice.ArrayOfLocationStruct locations {
            get {
                return this.locationsField;
            }
            set {
                if ((object.ReferenceEquals(this.locationsField, value) != true)) {
                    this.locationsField = value;
                    this.RaisePropertyChanged("locations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=20)]
        public sFTP2.webservice.carrierStruct carrier {
            get {
                return this.carrierField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierField, value) != true)) {
                    this.carrierField = value;
                    this.RaisePropertyChanged("carrier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public sFTP2.webservice.ArrayOfReferenceStruct reference {
            get {
                return this.referenceField;
            }
            set {
                if ((object.ReferenceEquals(this.referenceField, value) != true)) {
                    this.referenceField = value;
                    this.RaisePropertyChanged("reference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="carrierStruct", Namespace="http://dockmanager.eu/")]
    [System.SerializableAttribute()]
    public partial class carrierStruct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierRemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierVehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierTrailerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrivernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverRemarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierCodeField, value) != true)) {
                    this.carrierCodeField = value;
                    this.RaisePropertyChanged("carrierCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carrierRef {
            get {
                return this.carrierRefField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierRefField, value) != true)) {
                    this.carrierRefField = value;
                    this.RaisePropertyChanged("carrierRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string carrierName {
            get {
                return this.carrierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierNameField, value) != true)) {
                    this.carrierNameField = value;
                    this.RaisePropertyChanged("carrierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string carrierAddress {
            get {
                return this.carrierAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierAddressField, value) != true)) {
                    this.carrierAddressField = value;
                    this.RaisePropertyChanged("carrierAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string carrierCity {
            get {
                return this.carrierCityField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierCityField, value) != true)) {
                    this.carrierCityField = value;
                    this.RaisePropertyChanged("carrierCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string carrierPostalCode {
            get {
                return this.carrierPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierPostalCodeField, value) != true)) {
                    this.carrierPostalCodeField = value;
                    this.RaisePropertyChanged("carrierPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string carrierCountry {
            get {
                return this.carrierCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierCountryField, value) != true)) {
                    this.carrierCountryField = value;
                    this.RaisePropertyChanged("carrierCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string carrierContact {
            get {
                return this.carrierContactField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierContactField, value) != true)) {
                    this.carrierContactField = value;
                    this.RaisePropertyChanged("carrierContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string carrierPhone {
            get {
                return this.carrierPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierPhoneField, value) != true)) {
                    this.carrierPhoneField = value;
                    this.RaisePropertyChanged("carrierPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string carrierMail {
            get {
                return this.carrierMailField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierMailField, value) != true)) {
                    this.carrierMailField = value;
                    this.RaisePropertyChanged("carrierMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string carrierRemarks {
            get {
                return this.carrierRemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierRemarksField, value) != true)) {
                    this.carrierRemarksField = value;
                    this.RaisePropertyChanged("carrierRemarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string carrierVehicle {
            get {
                return this.carrierVehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierVehicleField, value) != true)) {
                    this.carrierVehicleField = value;
                    this.RaisePropertyChanged("carrierVehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string carrierTrailer {
            get {
                return this.carrierTrailerField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierTrailerField, value) != true)) {
                    this.carrierTrailerField = value;
                    this.RaisePropertyChanged("carrierTrailer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Drivername {
            get {
                return this.DrivernameField;
            }
            set {
                if ((object.ReferenceEquals(this.DrivernameField, value) != true)) {
                    this.DrivernameField = value;
                    this.RaisePropertyChanged("Drivername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string DriverPhone {
            get {
                return this.DriverPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverPhoneField, value) != true)) {
                    this.DriverPhoneField = value;
                    this.RaisePropertyChanged("DriverPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DriverMail {
            get {
                return this.DriverMailField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverMailField, value) != true)) {
                    this.DriverMailField = value;
                    this.RaisePropertyChanged("DriverMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string DriverRemarks {
            get {
                return this.DriverRemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverRemarksField, value) != true)) {
                    this.DriverRemarksField = value;
                    this.RaisePropertyChanged("DriverRemarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLocationStruct", Namespace="http://dockmanager.eu/", ItemName="locationStruct")]
    [System.SerializableAttribute()]
    public class ArrayOfLocationStruct : System.Collections.Generic.List<sFTP2.webservice.locationStruct> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfReferenceStruct", Namespace="http://dockmanager.eu/", ItemName="referenceStruct")]
    [System.SerializableAttribute()]
    public class ArrayOfReferenceStruct : System.Collections.Generic.List<sFTP2.webservice.referenceStruct> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="locationStruct", Namespace="http://dockmanager.eu/")]
    [System.SerializableAttribute()]
    public partial class locationStruct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationPostalcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locatonMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationDirectionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationRemarksField;
        
        private System.DateTime locationDateTime1Field;
        
        private System.DateTime locationDateTime2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string locationID {
            get {
                return this.locationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.locationIDField, value) != true)) {
                    this.locationIDField = value;
                    this.RaisePropertyChanged("locationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.locationNameField, value) != true)) {
                    this.locationNameField = value;
                    this.RaisePropertyChanged("locationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string locationAddress {
            get {
                return this.locationAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.locationAddressField, value) != true)) {
                    this.locationAddressField = value;
                    this.RaisePropertyChanged("locationAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string locationPostalcode {
            get {
                return this.locationPostalcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.locationPostalcodeField, value) != true)) {
                    this.locationPostalcodeField = value;
                    this.RaisePropertyChanged("locationPostalcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string locationCity {
            get {
                return this.locationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.locationCityField, value) != true)) {
                    this.locationCityField = value;
                    this.RaisePropertyChanged("locationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string locationCountry {
            get {
                return this.locationCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.locationCountryField, value) != true)) {
                    this.locationCountryField = value;
                    this.RaisePropertyChanged("locationCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string locationContact {
            get {
                return this.locationContactField;
            }
            set {
                if ((object.ReferenceEquals(this.locationContactField, value) != true)) {
                    this.locationContactField = value;
                    this.RaisePropertyChanged("locationContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string locationPhone {
            get {
                return this.locationPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.locationPhoneField, value) != true)) {
                    this.locationPhoneField = value;
                    this.RaisePropertyChanged("locationPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string locatonMail {
            get {
                return this.locatonMailField;
            }
            set {
                if ((object.ReferenceEquals(this.locatonMailField, value) != true)) {
                    this.locatonMailField = value;
                    this.RaisePropertyChanged("locatonMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string locationDirections {
            get {
                return this.locationDirectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.locationDirectionsField, value) != true)) {
                    this.locationDirectionsField = value;
                    this.RaisePropertyChanged("locationDirections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string locationRemarks {
            get {
                return this.locationRemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.locationRemarksField, value) != true)) {
                    this.locationRemarksField = value;
                    this.RaisePropertyChanged("locationRemarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime locationDateTime1 {
            get {
                return this.locationDateTime1Field;
            }
            set {
                if ((this.locationDateTime1Field.Equals(value) != true)) {
                    this.locationDateTime1Field = value;
                    this.RaisePropertyChanged("locationDateTime1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime locationDateTime2 {
            get {
                return this.locationDateTime2Field;
            }
            set {
                if ((this.locationDateTime2Field.Equals(value) != true)) {
                    this.locationDateTime2Field = value;
                    this.RaisePropertyChanged("locationDateTime2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="referenceStruct", Namespace="http://dockmanager.eu/")]
    [System.SerializableAttribute()]
    public partial class referenceStruct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ref_qualifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ref_valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ref_qualifier {
            get {
                return this.ref_qualifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ref_qualifierField, value) != true)) {
                    this.ref_qualifierField = value;
                    this.RaisePropertyChanged("ref_qualifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ref_value {
            get {
                return this.ref_valueField;
            }
            set {
                if ((object.ReferenceEquals(this.ref_valueField, value) != true)) {
                    this.ref_valueField = value;
                    this.RaisePropertyChanged("ref_value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://dockmanager.eu/")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseField;
        
        private System.DateTime processedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageNumber {
            get {
                return this.MessageNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageNumberField, value) != true)) {
                    this.MessageNumberField = value;
                    this.RaisePropertyChanged("MessageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string response {
            get {
                return this.responseField;
            }
            set {
                if ((object.ReferenceEquals(this.responseField, value) != true)) {
                    this.responseField = value;
                    this.RaisePropertyChanged("response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime processed {
            get {
                return this.processedField;
            }
            set {
                if ((this.processedField.Equals(value) != true)) {
                    this.processedField = value;
                    this.RaisePropertyChanged("processed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dockmanager.eu/", ConfigurationName="webservice.DMWSSoap")]
    public interface DMWSSoap {
        
        // CODEGEN: Generating message contract since element name login from namespace http://dockmanager.eu/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dockmanager.eu/retrieve_realisations", ReplyAction="*")]
        sFTP2.webservice.retrieve_realisationsResponse retrieve_realisations(sFTP2.webservice.retrieve_realisationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dockmanager.eu/retrieve_realisations", ReplyAction="*")]
        System.Threading.Tasks.Task<sFTP2.webservice.retrieve_realisationsResponse> retrieve_realisationsAsync(sFTP2.webservice.retrieve_realisationsRequest request);
        
        // CODEGEN: Generating message contract since element name calloff from namespace http://dockmanager.eu/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dockmanager.eu/Reservation", ReplyAction="*")]
        sFTP2.webservice.ReservationResponse Reservation(sFTP2.webservice.ReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dockmanager.eu/Reservation", ReplyAction="*")]
        System.Threading.Tasks.Task<sFTP2.webservice.ReservationResponse> ReservationAsync(sFTP2.webservice.ReservationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieve_realisationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retrieve_realisations", Namespace="http://dockmanager.eu/", Order=0)]
        public sFTP2.webservice.retrieve_realisationsRequestBody Body;
        
        public retrieve_realisationsRequest() {
        }
        
        public retrieve_realisationsRequest(sFTP2.webservice.retrieve_realisationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dockmanager.eu/")]
    public partial class retrieve_realisationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public sFTP2.webservice.LoginData login;
        
        public retrieve_realisationsRequestBody() {
        }
        
        public retrieve_realisationsRequestBody(System.DateTime dt, sFTP2.webservice.LoginData login) {
            this.dt = dt;
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieve_realisationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retrieve_realisationsResponse", Namespace="http://dockmanager.eu/", Order=0)]
        public sFTP2.webservice.retrieve_realisationsResponseBody Body;
        
        public retrieve_realisationsResponse() {
        }
        
        public retrieve_realisationsResponse(sFTP2.webservice.retrieve_realisationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dockmanager.eu/")]
    public partial class retrieve_realisationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sFTP2.webservice.ArrayOfBooking retrieve_realisationsResult;
        
        public retrieve_realisationsResponseBody() {
        }
        
        public retrieve_realisationsResponseBody(sFTP2.webservice.ArrayOfBooking retrieve_realisationsResult) {
            this.retrieve_realisationsResult = retrieve_realisationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reservation", Namespace="http://dockmanager.eu/", Order=0)]
        public sFTP2.webservice.ReservationRequestBody Body;
        
        public ReservationRequest() {
        }
        
        public ReservationRequest(sFTP2.webservice.ReservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dockmanager.eu/")]
    public partial class ReservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sFTP2.webservice.CallOff calloff;
        
        public ReservationRequestBody() {
        }
        
        public ReservationRequestBody(sFTP2.webservice.CallOff calloff) {
            this.calloff = calloff;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservationResponse", Namespace="http://dockmanager.eu/", Order=0)]
        public sFTP2.webservice.ReservationResponseBody Body;
        
        public ReservationResponse() {
        }
        
        public ReservationResponse(sFTP2.webservice.ReservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dockmanager.eu/")]
    public partial class ReservationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public sFTP2.webservice.Response ReservationResult;
        
        public ReservationResponseBody() {
        }
        
        public ReservationResponseBody(sFTP2.webservice.Response ReservationResult) {
            this.ReservationResult = ReservationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DMWSSoapChannel : sFTP2.webservice.DMWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DMWSSoapClient : System.ServiceModel.ClientBase<sFTP2.webservice.DMWSSoap>, sFTP2.webservice.DMWSSoap {
        
        public DMWSSoapClient() {
        }
        
        public DMWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DMWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sFTP2.webservice.retrieve_realisationsResponse sFTP2.webservice.DMWSSoap.retrieve_realisations(sFTP2.webservice.retrieve_realisationsRequest request) {
            return base.Channel.retrieve_realisations(request);
        }
        
        public sFTP2.webservice.ArrayOfBooking retrieve_realisations(System.DateTime dt, sFTP2.webservice.LoginData login) {
            sFTP2.webservice.retrieve_realisationsRequest inValue = new sFTP2.webservice.retrieve_realisationsRequest();
            inValue.Body = new sFTP2.webservice.retrieve_realisationsRequestBody();
            inValue.Body.dt = dt;
            inValue.Body.login = login;
            sFTP2.webservice.retrieve_realisationsResponse retVal = ((sFTP2.webservice.DMWSSoap)(this)).retrieve_realisations(inValue);
            return retVal.Body.retrieve_realisationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sFTP2.webservice.retrieve_realisationsResponse> sFTP2.webservice.DMWSSoap.retrieve_realisationsAsync(sFTP2.webservice.retrieve_realisationsRequest request) {
            return base.Channel.retrieve_realisationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<sFTP2.webservice.retrieve_realisationsResponse> retrieve_realisationsAsync(System.DateTime dt, sFTP2.webservice.LoginData login) {
            sFTP2.webservice.retrieve_realisationsRequest inValue = new sFTP2.webservice.retrieve_realisationsRequest();
            inValue.Body = new sFTP2.webservice.retrieve_realisationsRequestBody();
            inValue.Body.dt = dt;
            inValue.Body.login = login;
            return ((sFTP2.webservice.DMWSSoap)(this)).retrieve_realisationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sFTP2.webservice.ReservationResponse sFTP2.webservice.DMWSSoap.Reservation(sFTP2.webservice.ReservationRequest request) {
            return base.Channel.Reservation(request);
        }
        
        public sFTP2.webservice.Response Reservation(sFTP2.webservice.CallOff calloff) {
            sFTP2.webservice.ReservationRequest inValue = new sFTP2.webservice.ReservationRequest();
            inValue.Body = new sFTP2.webservice.ReservationRequestBody();
            inValue.Body.calloff = calloff;
            sFTP2.webservice.ReservationResponse retVal = ((sFTP2.webservice.DMWSSoap)(this)).Reservation(inValue);
            return retVal.Body.ReservationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sFTP2.webservice.ReservationResponse> sFTP2.webservice.DMWSSoap.ReservationAsync(sFTP2.webservice.ReservationRequest request) {
            return base.Channel.ReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<sFTP2.webservice.ReservationResponse> ReservationAsync(sFTP2.webservice.CallOff calloff) {
            sFTP2.webservice.ReservationRequest inValue = new sFTP2.webservice.ReservationRequest();
            inValue.Body = new sFTP2.webservice.ReservationRequestBody();
            inValue.Body.calloff = calloff;
            return ((sFTP2.webservice.DMWSSoap)(this)).ReservationAsync(inValue);
        }
    }
}
